Add project files
badger-99/to-do_list_-peerReview pull request #1
Opened 2023-06-20 12:23 UTC by badger-99

In this PR I add all the files for this project including:
* Source files
* Github workflow file
* Linter config files
* Webpack config file
* Complete documentatioin
* License information
* Dist folder
* Package.JSON
* Package-lock.JSON

2023-06-20 13:27 UTC, habitoz requested changes
# Hi @badger-99 ,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.

## Required Changes ♻️

 - [ ] Kindly add a descriptive pull request message, This helps other programmers who want to take a look at your code to understand what changes you made to a particular branch,
 - [ ]  it would be great if you can structure your your files in a folder.like organizing your js files in one folder.

 _Check the comments under the review for more changes_.

## Optional suggestions
- [ ] you don't have to create a new file for every function you are going to have.it is good practice to group related functions together especially for simple functions.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-06-20 13:27 UTC, habitoz commented on src/utilityFunctions.js
> +export default UtilityFunctions;
this class has methods that are all static and there is no data in the class.i think it would be better if we could replace the class with multiple functions rather than static methods as this adds extra complexity. again this also violates the KISS rule.

2023-06-20 13:27 UTC, habitoz commented on src/index.js
> +taskArray = [...UtilityFunctions.getStorage()];
UtilityFunction.getStorage() already returns an array i don't see the reason why you spread it we can use the returned array.

2023-06-20 15:58 UTC, badger-99 commented on src/form-top-and-bottom.js
> +const heading = document.createElement('div');
The reason I this was because the project requirements stated that we were to only have one `div` or `ul` container and the rest had to be added dynamically. I would have also chosen the simpler path, but after having a code reviewer request changes that nearly broke my entire project in the past, I decided to use caution. The complexity was a result of the project requirements.

2023-06-20 16:05 UTC, badger-99 commented on src/utilityFunctions.js
> +export default UtilityFunctions;
In my opinion, I don't believe that having multiple functions has any real advantage over having them as multiple static functions within one utility class. Additionally, I believe my method is actually less complicated since a lot of those functions depend on each other as well as the local storage. Having them in one class allows me to use the member functions in other functions with ease by using the `this` keyword. However, if you have documentation that shows otherwise, I would be willing to take a look at it.

2023-06-22 09:48 UTC, habitoz approved these changes
# Hi @badger-99

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 
- Descriptive PR Title And Description ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------

2023-06-22 09:52 UTC, merged